
select count(*) from region;
select count(*) from nation;
select count(*) from part;
select count(*) from supplier;
select count(*) from partsupp;
select count(*) from customer;
select count(*) from orders;
select count(*) from lineitem;

select avg(length(R_NAME)) from region;
select avg(length(R_COMMENT)) from region;

select avg(length(N_NAME)) from nation;
select avg(length(N_COMMENT)) from nation;

select avg(length(P_NAME)) from part;
select avg(length(P_MFGR)) from part;
select avg(length(P_BRAND)) from part;
select avg(length(P_TYPE)) from part;
select min(P_SIZE) from part;
select max(P_SIZE) from part;
select count(distinct(P_SIZE)) from part;
select avg(length(P_CONTAINER)) from part;
select min(P_RETAILPRICE) from part;
select max(P_RETAILPRICE) from part;
select avg(length(P_COMMENT)) from part;

select avg(length(S_NAME)) from supplier;
select avg(length(S_ADDRESS)) from supplier;
select avg(length(S_PHONE)) from supplier;
select min(S_ACCTBAL) from supplier;
select max(S_ACCTBAL) from supplier;
select avg(length(S_COMMENT)) from supplier;

select min(PS_AVAILQTY) from partsupp;
select max(PS_AVAILQTY) from partsupp;
select count(distinct(PS_AVAILQTY)) from partsupp;
select count(*) from partsupp where PS_AVAILQTY is null;
select min(PS_SUPPLYCOST) from partsupp;
select max(PS_SUPPLYCOST) from partsupp;
select count(*) from partsupp where PS_SUPPLYCOST is null;
select avg(length(PS_COMMENT)) from partsupp;
select count(*) from partsupp where PS_COMMENT is null;

select avg(length(C_NAME)) from customer;
select count(*) from customer where C_NAME is null;
select avg(length(C_ADDRESS)) from customer;
select count(*) from customer where C_ADDRESS is null;
select avg(length(C_PHONE)) from customer;
select count(*) from customer where C_PHONE is null;
select min(C_ACCTBAL) from customer;
select max(C_ACCTBAL) from customer;
select count(*) from customer where C_ACCTBAL is null;
select avg(length(C_MKTSEGMENT)) from customer;
select count(*) from customer where C_MKTSEGMENT is null;
select avg(length(C_COMMENT)) from customer;
select count(*) from customer where C_COMMENT is null;

select avg(length(O_ORDERSTATUS)) from orders;
select min(O_TOTALPRICE) from orders;
select max(O_TOTALPRICE) from orders;
select count(*) from orders where O_TOTALPRICE is null;
select min(O_ORDERDATE) from orders;
select count(*) from orders where O_ORDERDATE is null;
select max(O_ORDERDATE) from orders;
select avg(length(O_ORDERPRIORITY)) from orders;
select avg(length(O_CLERK)) from orders;
select count(*) from orders where O_CLERK is null;
select min(O_SHIPPRIORITY) from orders;
select max(O_SHIPPRIORITY) from orders;
select count(distinct(O_SHIPPRIORITY)) from orders;
select count(*) from orders where O_SHIPPRIORITY is null;
select avg(length(O_COMMENT)) from orders;
select count(*) from orders where o_comment is null;

select min(L_QUANTITY) from lineitem;
select max(L_QUANTITY) from lineitem;
select count(*) from lineitem where l_quantity is null;
select min(L_EXTENDEDPRICE) from lineitem;
select max(L_EXTENDEDPRICE) from lineitem;
select count(*) from lineitem where L_EXTENDEDPRICE is null;
select min(L_DISCOUNT) from lineitem;
select max(L_DISCOUNT) from lineitem;
select count(*) from lineitem where L_DISCOUNT is null;
select min(L_TAX) from lineitem;
select max(L_TAX) from lineitem;
select count(*) from lineitem where L_TAX is null;
select avg(length(L_RETURNFLAG)) from lineitem;
select count(*) from lineitem where L_RETURNFLAG is null;
select avg(length(L_LINESTATUS)) from lineitem;
select count(*) from lineitem where L_LINESTATUS is null;
select min(L_SHIPDATE) from lineitem;
select max(L_SHIPDATE) from lineitem;
select count(*) from lineitem where L_SHIPDATE is null;
select min(L_COMMITDATE) from lineitem;
select max(L_COMMITDATE) from lineitem;
select min(L_RECEIPTDATE) from lineitem;
select max(L_RECEIPTDATE) from lineitem;
select count(*) from lineitem where L_RECEIPTDATE is null;
select avg(length(L_SHIPINSTRUCT)) from lineitem;
select count(*) from lineitem where L_SHIPINSTRUCT is null;
select avg(length(L_SHIPMODE)) from lineitem;
select count(*) from lineitem where L_SHIPMODE is null;
select avg(length(L_COMMENT)) from lineitem;
select count(*) from lineitem where L_COMMENT is null;
