package edu.ecnu.touchstone.rule;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

import edu.ecnu.touchstone.extractor.FilterOpInfo;
import edu.ecnu.touchstone.extractor.FkInfo;
import edu.ecnu.touchstone.extractor.Info;
import edu.ecnu.touchstone.extractor.PkInfo;
import edu.ecnu.touchstone.extractor.Query;
import edu.ecnu.touchstone.run.Touchstone;
import net.sf.jsqlparser.expression.*;
import net.sf.jsqlparser.expression.operators.relational.*;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.schema.Column;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.select.*;

public class Rule {
    private Logger logger = null;

    public Rule() {
        logger = Logger.getLogger(Touchstone.class);
    }

    public static List<Rule> NQcase(SelectBody selectBody) {
        List<Rule> rules = new ArrayList<>();
        // set operations
        if (selectBody instanceof SetOperationList) {

        }
        else if (selectBody instanceof PlainSelect) {
            PlainSelect plainSelect = (PlainSelect) selectBody;
            // select
            List<SelectItem> selectItems = plainSelect.getSelectItems();
            for (SelectItem selectItem: selectItems) {
                if (selectItem.toString().contains("select")) {

                }
            }
            // from
            FromItem from = plainSelect.getFromItem();
            if (from instanceof SubSelect) {
                rules.add(new FromRule());
            }
            // where
            Expression where = plainSelect.getWhere();
            if (where != null && where.toString().contains("select")) {
                where.accept(new ExpressionVisitorAdapter() {
                    @Override 
                    public void visit(InExpression inExpression) {
                        if (inExpression.toString().contains("select")) {
                            if (inExpression.isNot()) {
                                rules.add(new NotInRule());
                            } else {
                                rules.add(new InRule());
                            }
                        }
                    }
                    @Override
                    public void visit(ExistsExpression existExpression) {
                        if (existExpression.toString().contains("select")) {
                            if (existExpression.isNot()) {
                                rules.add(new NotExistRule());
                            } else {
                                rules.add(new ExistRule());
                            }

                        }
                    }
                });
            }
            // having
            Expression having = plainSelect.getHaving();
            if (having != null) {

            }
        } else if (selectBody instanceof WithItem) {

        } else {

        }
        return rules;
    }

    /* 
     * @Input: a flat Select query (e.g., no WITH ..., CREATE ...)
     * @Output: a list of ConstraintChain generated by this query 
     */
    public List<Info> parse(Query query) {
        Statement stmt = query.getStmt();
        Select select = (Select) stmt;
        SelectBody selectBody = select.getSelectBody();
        PlainSelect plainSelect = (PlainSelect) selectBody;
        List<Info> ret = new ArrayList<>();
        // where 
        Expression where = plainSelect.getWhere();
        if (where != null) {
            ret.addAll(parseExpression(where));
        }
        // join
        List<Join> joinList = plainSelect.getJoins();
        if (joinList != null) {
            for (Join join: joinList) {
                List<Expression> onExprs = (List<Expression>) join.getOnExpressions();  
                for (Expression onExpr: onExprs) {
                    List<Info> conditions = parseExpression(onExpr);
                    ret.addAll(conditions);
                }
            }
        }
        //having
        Expression having = plainSelect.getHaving();
        if (having != null) {
            List<Info> conditions = parseExpression(having);
            ret.addAll(conditions);
        }
        return ret;
    }

    /*
     * @Input: Expression
     * @Description: parse all conditions in where
     * @Return: FilterOp and JoinInformations
     */
    public List<Info> parseExpression(Expression expr) {
        List<Info> infos = new ArrayList<>();
        expr.accept(new ExpressionVisitorAdapter() {

            @Override 
            public void visit(InExpression inExpression) {
                String operator = (inExpression.isNot()) ? "not in" : "in";
                FilterOpInfo filterOp = new FilterOpInfo(inExpression, operator);
                infos.add(filterOp);
            }

            @Override 
            public void visit(LikeExpression likeExpression) {
                String operator = (likeExpression.isNot()) ? "not like" : "like";
                FilterOpInfo filterOp = new FilterOpInfo(likeExpression, operator);
                infos.add(filterOp);
            }

            @Override 
            public void visit(NotEqualsTo notEqualsTo) {
                FilterOpInfo filterOp = new FilterOpInfo(notEqualsTo, "<>");
                infos.add(filterOp);
            }

            @Override
            public void visit(EqualsTo equalsTo) {
                if (isJoinCondition(equalsTo)) {
                    PkInfo pkInfo = new PkInfo(equalsTo);
                    FkInfo fkInfo = new FkInfo(pkInfo);
                    infos.add(pkInfo);
                    infos.add(fkInfo);
                } else {
                    FilterOpInfo filterOp = new FilterOpInfo(equalsTo, "=");
                    infos.add(filterOp);
                }
            }

            @Override 
            public void visit(GreaterThan greaterThan) {
                FilterOpInfo filterOp = new FilterOpInfo(greaterThan, ">");
                infos.add(filterOp);
            }

            @Override 
            public void visit(GreaterThanEquals greaterThanEquals) {
                FilterOpInfo filterOp = new FilterOpInfo(greaterThanEquals, ">=");
                infos.add(filterOp);
            }

            @Override
            public void visit(MinorThan minorThan) {
                FilterOpInfo filterOp = new FilterOpInfo(minorThan, "<");
                infos.add(filterOp);
            }

            @Override 
            public void visit(MinorThanEquals minorThanEquals) {
                FilterOpInfo filterOp = new FilterOpInfo(minorThanEquals, "<=");
                infos.add(filterOp);
            }
        });
        logger.info("\n Query Filter Ops are: [\n" + infos + "\n]");
        return infos;
    }

    /*
     * @Input: BinaryExpression like a = b, a >= b
     */
    public boolean isJoinCondition(BinaryExpression expr) {
        Expression left = expr.getLeftExpression();
        Expression right = expr.getRightExpression();
        return (left instanceof Column) && (right instanceof Column) 
                && (!right.toString().contains("$"));
    }

    public static void main(String[] args) {
        String sql = "select * from r join s on r.k1 = s.k2 join t on s.k3 = t.k4 where col in (1, 2, 3);";
        PropertyConfigurator.configure(".//test//lib//log4j.properties");
        try {
            Statement stmt = CCJSqlParserUtil.parse(sql);
            Select select = (Select) stmt;
            PlainSelect plainSelect = (PlainSelect) select.getSelectBody();
            Expression expr = plainSelect.getWhere();
            expr.accept(new ExpressionVisitorAdapter() {
                @Override
                public void visit(InExpression inExpr) {
                    System.out.println(inExpr);
                    System.out.println(inExpr.getLeftExpression());
                    System.out.println(inExpr.getRightItemsList());
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
